[package]
name = "rustrest"
version = "0.1.0"
authors = ["Kevin Fleming <kvnflm@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
attohttpc = "0.13.0"
clap = "2.33.0"
serde = { version = "1.0.106", features = ["derive"] }
toml = "0.5.6"

[dev-dependencies]
criterion = "0.3.2"

[[bench]]
name = "templating"
harness = false
