[package]
name = "rustrest"
version = "0.1.0"
authors = ["Kevin Fleming <kvnflm@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
clap = "2.33.0"
reqwest = { version = "0.10.4", features = ["blocking"] }
serde = { version = "1.0.106", features = ["derive"] }
toml = "0.5.6"
