[metadata]
description = "httpbin post"

[request]
url = "https://httpbin.org/post"
method = "POST"

[body]
type = "json"
content = '''
{
  "some_key": "some value",
  "a_number": 123,
  "nested": {
    "inside": true,
    "other": null
  }
}'''
