[request]
url = "https://httpbin.org/post"
method = "POST"

[body]
content_type = 'multipart/form-data;boundary="boundary"'
content = '''
--boundary 
Content-Disposition: form-data; name="field1" 

value1 
--boundary 
Content-Disposition: form-data; name="field2"; filename="example.txt" 

value2
--boundary--'''
